/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppCompaniesIndexRouteImport } from './routes/_app/companies/index'
import { Route as AppCampaignsIndexRouteImport } from './routes/_app/campaigns/index'
import { Route as ApiWebhooksInstantlyRouteImport } from './routes/api/webhooks/instantly'
import { Route as AppCompaniesImportRouteImport } from './routes/_app/companies/import'
import { Route as AppCompaniesCompanyIdRouteImport } from './routes/_app/companies/$companyId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCompaniesIndexRoute = AppCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiWebhooksInstantlyRoute = ApiWebhooksInstantlyRouteImport.update({
  id: '/api/webhooks/instantly',
  path: '/api/webhooks/instantly',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompaniesImportRoute = AppCompaniesImportRouteImport.update({
  id: '/companies/import',
  path: '/companies/import',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCompaniesCompanyIdRoute = AppCompaniesCompanyIdRouteImport.update({
  id: '/companies/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/companies/import': typeof AppCompaniesImportRoute
  '/api/webhooks/instantly': typeof ApiWebhooksInstantlyRoute
  '/campaigns/': typeof AppCampaignsIndexRoute
  '/companies/': typeof AppCompaniesIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/companies/import': typeof AppCompaniesImportRoute
  '/api/webhooks/instantly': typeof ApiWebhooksInstantlyRoute
  '/campaigns': typeof AppCampaignsIndexRoute
  '/companies': typeof AppCompaniesIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/_app/companies/import': typeof AppCompaniesImportRoute
  '/api/webhooks/instantly': typeof ApiWebhooksInstantlyRoute
  '/_app/campaigns/': typeof AppCampaignsIndexRoute
  '/_app/companies/': typeof AppCompaniesIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies/$companyId'
    | '/companies/import'
    | '/api/webhooks/instantly'
    | '/campaigns/'
    | '/companies/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies/$companyId'
    | '/companies/import'
    | '/api/webhooks/instantly'
    | '/campaigns'
    | '/companies'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/companies/$companyId'
    | '/_app/companies/import'
    | '/api/webhooks/instantly'
    | '/_app/campaigns/'
    | '/_app/companies/'
    | '/_app/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ApiWebhooksInstantlyRoute: typeof ApiWebhooksInstantlyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/companies/': {
      id: '/_app/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof AppCompaniesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/campaigns/': {
      id: '/_app/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/webhooks/instantly': {
      id: '/api/webhooks/instantly'
      path: '/api/webhooks/instantly'
      fullPath: '/api/webhooks/instantly'
      preLoaderRoute: typeof ApiWebhooksInstantlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/companies/import': {
      id: '/_app/companies/import'
      path: '/companies/import'
      fullPath: '/companies/import'
      preLoaderRoute: typeof AppCompaniesImportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/companies/$companyId': {
      id: '/_app/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof AppCompaniesCompanyIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppCompaniesCompanyIdRoute: typeof AppCompaniesCompanyIdRoute
  AppCompaniesImportRoute: typeof AppCompaniesImportRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
  AppCompaniesIndexRoute: typeof AppCompaniesIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCompaniesCompanyIdRoute: AppCompaniesCompanyIdRoute,
  AppCompaniesImportRoute: AppCompaniesImportRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
  AppCompaniesIndexRoute: AppCompaniesIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ApiWebhooksInstantlyRoute: ApiWebhooksInstantlyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
